# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171010_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerlist',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=6),
        ),
        migrations.AlterField(
            model_name='playerlist',
            name='palyer_type',
            field=models.CharField(choices=[('BATING', 'Bating'), ('BOWLER', 'Bowler'), ('ALLROUNDER', 'All Rounder'), ('KEEPER', 'Keeper')], default='BOWLER', max_length=10),
        ),
    ]
