# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171010_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='playerlist',
            name='home_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.DistrictList'),
            preserve_default=False,
        ),
    ]
