# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_productcategory_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='created_by',
            new_name='updated_by',
        ),
    ]
